services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: razum
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: razumly
    ports: [ "5432:5432" ]
    volumes: [ db-data:/var/lib/postgresql/data ]

  redis:
    image: redis:7
    restart: unless-stopped
    ports: [ "6379:6379" ]

  api:
    build: .
    image: razumly-backend:latest
    restart: unless-stopped
    env_file: .env
    depends_on: [ db, redis ]
    ports: [ "4000:4000" ]
    environment:
      - DATABASE_URL=postgresql://razum:secret@db:5432/razumly

  worker:
    image: razumly-backend:latest
    command: node dist/worker.main.js
    restart: unless-stopped
    env_file: .env
    depends_on: [ db, redis ]

volumes:
  db-data:
